import { QueryProvider } from "@/components/client/ReactQuery";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClientProvider } from "@/components/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body tabIndex={0} className={inter.className}>
        <QueryProvider>
          <ClientProvider>{children}</ClientProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
