import { QueryProvider } from "@/components/client/ReactQuery";
import "../globals.css";
import { Inter } from "next/font/google";
import { ClientProvider } from "@/components/client";
import { redirect } from "next/navigation";
import { Analytics } from "@/components/component/Analytics";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={{
        scrollBehavior: "smooth",
      }}
    >
      <head>
        <Analytics />
      </head>
      <body tabIndex={0} className={inter.className}>
        <QueryProvider>
          <ClientProvider>{children}</ClientProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
