import { Analytics } from "@/components/component/Analytics";
import "../../globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={{
        scrollBehavior: "smooth",
      }}
    >
      <head>
        <Analytics />
      </head>
      <body tabIndex={0} className={inter.className}>
        {children}
      </body>
    </html>
  );
}
