import { Analytics } from "@/components/component/Analytics";
import "../../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={{
        scrollBehavior: "smooth",
      }}
    >
      <head>
        <Analytics />
      </head>
      <body tabIndex={0}>{children}</body>
    </html>
  );
}
