import { QueryProvider } from "@/components/client/ReactQuery";
import "../globals.css";
import { ClientProvider } from "@/components/client";
import { redirect } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={{
        scrollBehavior: "smooth",
      }}
    >
      <body tabIndex={0}>{children}</body>
    </html>
  );
}
